### ISSUE TITLE
jscs, jscs-loader needed

### ISSUE THREAD

**Issue by dylang** [swennemans/isoose#2]
```
npm run build

> iso-start@0.0.1 build /Users/dylang/projects/isoose
> webpack --progress --stats --config ./webpack/prod.config.js

Hash: 0bbe310af3ea14922b97
Version: webpack 1.9.8
Time: 54ms

ERROR in Entry module not found: Error: Cannot resolve module 'jscs' in /Users/dgreene/projects/reaction/isoose
```
Maybe needs `jscs` and `jscs-loader` in the `package.json`?
 `npm i jscs jscs-loader -D`

**Comment by dylang** [comment]
Maybe that's not right, I get a new error

```
ERROR in ./app/index.js
Module build failed: TypeError: this._createConfiguration is not a function
    at Object.StringChecker (/Users/dgreene/projects/reaction/isoose/node_modules/jscs/lib/string-checker.js:26:32)
    at Object.Checker (/Users/dgreene/projects/reaction/isoose/node_modules/jscs/lib/checker.js:15:19)
```

**Comment by swennemans** [comment]
Ah i see. I wanted to disable jscs/jscs-loader because it doesn't play well with some babel/es7 functionalities. I've disabled it for now, untill jscs-babel will be finished. 
If you dont use statics, it wont be a problem :)
